### ISSUE TITLE
calcTPM must match tsv file

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#17]
need to rwite a test for calcTPM to ensure that the tpm calculation is correct with respect to kallisto versions.

**Comment by arcolombo** [comment]
[Tpm-Err.pdf](https://github.com/RamsinghLab/arkas/files/358106/Tpm-Err.pdf)

**Comment by arcolombo** [comment]
[Tpm-Err.pdf](https://github.com/RamsinghLab/arkas/files/358108/Tpm-Err.pdf)

this shows the functoin calcTPM versus the generic accessor tpm(), so I'm not sure how @ttriche hit an error.   collapseTpm() uses tpm accessor and this plot shows its identical.  I'm suspecting it was a version clash.?   needs some data to reproduce @triche's issue....

**Comment by ttriche** [comment]
calcTpm is used to feed the matrix that tpm() pulls from, so those will
always be identical.  At some point there was a regression propagated from
HEAD (RamsinghLab/arkas) into my fork, which had not previously been there,
and had thrown off the calculations.  It turns out that leaving the TPM
calculation to the last minute (i.e., within the KallistoExperiment()
constructor) is faster and less error-prone, as is carving out the
calculation into its own little function that handles matrices and vectors
(row/column matrices) directly.  Hence calcTpm.

I spot-checked this on TARGET AML samples locally and I get no differences
greater than 0.0001 TPM, which is well within the margin of error due to
rounding/truncation.  calcTpm also has the benefit of corresponding exactly
(both variable names and logic) to that which Kallisto performs internally.

--t

**Comment by arcolombo** [comment]
so is this issue resolved? on my end I just used collapseTpm (yes it is a bit slow)...

**Comment by ttriche** [comment]
uh... collapseTpm should be using rowsum() to collapse... if it isn't, then
it will be slow.  I worry that a lot of changes from my branch seem to have
disappeared.

collapseTpm() is for gene-level or bundle-level (e.g. shared-ish TSS)
analyses; it has little or nothing to do with the problem at hand.  The
issue was that when I ran a few hundred samples into arkas from h5 files,
the version in HEAD was giving me nonsensical values that did not match up
to the values from the .TSV file for the same transcripts in the same
sample.

Here is the test I added to the reload script:

# double-check that the TPM fix did not somehow get mangled (again)

  load(file="~/TARGET/kallisto/FDFT1_txs.rda") # txs for testing
  PASJEJ <- targetRnaSeq[FDFT1_txs, "PASJEJ"]
  PASJEJ_FDFT1 <- data.frame(eff_length=eff_length(PASJEJ),
                             est_counts=counts(PASJEJ),
                             tpm=tpm(PASJEJ))
  load(file="~/TARGET/kallisto/FDFT1_PASJEJ.rda") # tpms for testing
  tpm_diffs <- (PASJEJ_FDFT1 - FDFT1_PASJEJ)[,3]
  if(any(tpm_diffs > 0.1)) stop("TPM calculations are wrong.  Aborting.")
  saveRDS(targetRnaSeq, file="~/TARGET/kallisto/targetRnaSeq.rds")

With the fixes I added to my pull request, it passes (for any subject).

--t

**Comment by arcolombo** [comment]
okay, your recent PR has been merged.

**Comment by arcolombo** [comment]
the collapseTPM uses an lapply and a colSums to group the non-empty tpm entries that have a sufficient feature data for the bundleID.   then it extracts via tpm()  which is what Arkas data sets have using.

the issue was **_only**_ with the results from calcTPM?  if so, then we can close this without revisiting previous data.... etc

AC

**Comment by ttriche** [comment]
this issue can be closed, performance of collapseTPM is a separate issue

--t

**Comment by arcolombo** [comment]
ok tyvm.
